import { Product, Category } from './types';

export const MOCK_PHONES: Product[] = [
  {
    id: '1',
    model: 'iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'Phones',
    price: 849,
    originalPrice: 1199,
    grade: 'Pristine',
    batteryHealth: 98,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/iphone-15-pro-max.png',
    galleryImages: [
      '/assets/iphone-15-pro-max.png',
      '/assets/YUYFZeFzWLMA.png',
      '/assets/xKrBA0WkKCOR.jpg',
      '/assets/y0wXjoNpojxp.png',
      '/assets/ybNb5k0B7nvc.png',
      '/assets/NGZkbbow4CIm.jpg',
    ],
    isCertified: true,
    stock: 5,
    conditionDescription: 'Like new condition with no visible scratches or blemishes. Battery health guaranteed above 95%. Complete with original box, charger, and all accessories. Professional refurbishment with 12-month warranty included.',
    specs: {
      network: 'GSM / CDMA / HSPA / EVDO / LTE / 5G',
      body: '159.9 x 76.7 x 8.3 mm, 221g; Glass front/back (Corning-made), titanium frame (grade 5)',
      display: '6.7" LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 2000 nits (peak)',
      platform: 'iOS 17, upgradable to iOS 17.4; Apple A17 Pro (3 nm); Hexa-core CPU; Apple GPU (6-core graphics)',
      storage: '256GB/512GB/1TB 8GB RAM, NVMe',
      mainCamera: '48 MP (wide) + 12 MP (periscope telephoto, 5x optical zoom) + 12 MP (ultrawide) + TOF 3D LiDAR scanner',
      selfieCamera: '12 MP (wide) + SL 3D (depth/biometrics sensor)',
      sound: 'Stereo speakers; No 3.5mm jack',
      comms: 'Wi-Fi 802.11 a/b/g/n/ac/6e, Bluetooth 5.3, NFC, USB Type-C 3.0',
      features: 'Face ID, accelerometer, gyro, proximity, compass, barometer; Ultra Wideband 2 (UWB) support',
      battery: 'Li-Ion 4441 mAh, non-removable; 50% in 30 min (advertised)'
    },
    colorOptions: ['Natural Titanium', 'Blue Titanium', 'White Titanium', 'Black Titanium'],
    storageOptions: ['256GB', '512GB', '1TB'],
    conditionOptions: ['Pristine', 'Excellent'],
    variants: [
      {
        id: '1-nt-256-pristine',
        color: 'Natural Titanium',
        storage: '256GB',
        condition: 'Pristine',
        price: 849,
        originalPrice: 1199,
        stock: 5,
        batteryHealth: 98,
      },
      {
        id: '1-nt-512-pristine',
        color: 'Natural Titanium',
        storage: '512GB',
        condition: 'Pristine',
        price: 949,
        originalPrice: 1299,
        stock: 3,
        batteryHealth: 98,
      },
      {
        id: '1-nt-1tb-pristine',
        color: 'Natural Titanium',
        storage: '1TB',
        condition: 'Pristine',
        price: 1049,
        originalPrice: 1399,
        stock: 2,
        batteryHealth: 98,
      },
      {
        id: '1-bt-256-pristine',
        color: 'Blue Titanium',
        storage: '256GB',
        condition: 'Pristine',
        price: 849,
        originalPrice: 1199,
        stock: 4,
        batteryHealth: 98,
      },
      {
        id: '1-bt-512-pristine',
        color: 'Blue Titanium',
        storage: '512GB',
        condition: 'Pristine',
        price: 949,
        originalPrice: 1299,
        stock: 3,
        batteryHealth: 98,
      },
      {
        id: '1-wt-256-pristine',
        color: 'White Titanium',
        storage: '256GB',
        condition: 'Pristine',
        price: 849,
        originalPrice: 1199,
        stock: 6,
        batteryHealth: 98,
      },
      {
        id: '1-wt-512-pristine',
        color: 'White Titanium',
        storage: '512GB',
        condition: 'Pristine',
        price: 949,
        originalPrice: 1299,
        stock: 2,
        batteryHealth: 98,
      },
      {
        id: '1-bk-256-pristine',
        color: 'Black Titanium',
        storage: '256GB',
        condition: 'Pristine',
        price: 849,
        originalPrice: 1199,
        stock: 7,
        batteryHealth: 98,
      },
      {
        id: '1-bk-512-pristine',
        color: 'Black Titanium',
        storage: '512GB',
        condition: 'Pristine',
        price: 949,
        originalPrice: 1299,
        stock: 4,
        batteryHealth: 98,
      },
      {
        id: '1-bk-1tb-pristine',
        color: 'Black Titanium',
        storage: '1TB',
        condition: 'Pristine',
        price: 1049,
        originalPrice: 1399,
        stock: 1,
        batteryHealth: 98,
      },
      {
        id: '1-nt-256-excellent',
        color: 'Natural Titanium',
        storage: '256GB',
        condition: 'Excellent',
        price: 749,
        originalPrice: 1099,
        stock: 8,
        batteryHealth: 95,
      },
      {
        id: '1-bt-256-excellent',
        color: 'Blue Titanium',
        storage: '256GB',
        condition: 'Excellent',
        price: 749,
        originalPrice: 1099,
        stock: 5,
        batteryHealth: 95,
      }
    ]
  },
  {
    id: '2',
    model: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Phones',
    price: 949,
    originalPrice: 1249,
    grade: 'Pristine',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/samsung-s24-ultra.png',
    galleryImages: [
      '/assets/samsung-s24-ultra.png',
      '/assets/DRdEaOalbpKP.jpg',
      '/assets/NGZkbbow4CIm.jpg',
      '/assets/nnCyJ3CuEgYe.jpg',
      '/assets/xKrBA0WkKCOR.jpg',
    ],
    isCertified: true,
    stock: 8,
    conditionDescription: 'Pristine condition, basically brand new. S-Pen included with full functionality. Gorilla Glass Armor display in perfect condition. All features tested and working flawlessly. Includes original Samsung charger and complete packaging.',
    specs: {
      network: 'GSM / CDMA / HSPA / EVDO / LTE / 5G',
      body: '162.3 x 79 x 8.6 mm, 232g; Glass front (Gorilla Armor), glass back (Gorilla Glass), titanium frame',
      display: '6.8" Dynamic LTPO AMOLED 2X, 120Hz, HDR10+, 2600 nits (peak)',
      platform: 'Android 14, One UI 6.1; Qualcomm SM8650-AB Snapdragon 8 Gen 3 (4 nm)',
      storage: '256GB/512GB/1TB 12GB RAM, UFS 4.0',
      mainCamera: '200 MP (wide) + 50 MP (periscope telephoto, 5x optical) + 10 MP (telephoto, 3x optical) + 12 MP (ultrawide)',
      selfieCamera: '12 MP (wide)',
      sound: 'Stereo speakers; 32-bit/384kHz audio; Tuned by AKG',
      comms: 'Wi-Fi 802.11 a/b/g/n/ac/6e/7, Bluetooth 5.3, NFC, USB Type-C 3.2, DisplayPort 1.2',
      features: 'Fingerprint (under display, ultrasonic), Samsung DeX, Ultra Wideband (UWB) support',
      battery: 'Li-Ion 5000 mAh, non-removable; 45W wired, 15W wireless'
    },
    colorOptions: ['Space Black', 'Silver', 'Gold'],
    storageOptions: ['128GB', '256GB'],
    conditionOptions: ['Excellent', 'Good'],
    variants: [
      {
        id: '2-sb-128-excellent',
        color: 'Space Black',
        storage: '128GB',
        condition: 'Excellent',
        price: 629,
        originalPrice: 999,
        stock: 8,
        batteryHealth: 92,
      },
      {
        id: '2-sb-256-excellent',
        color: 'Space Black',
        storage: '256GB',
        condition: 'Excellent',
        price: 729,
        originalPrice: 1099,
        stock: 5,
        batteryHealth: 92,
      },
      {
        id: '2-sb-128-pristine',
        color: 'Space Black',
        storage: '128GB',
        condition: 'Pristine',
        price: 749,
        originalPrice: 1149,
        stock: 3,
        batteryHealth: 100,
      },
      {
        id: '2-sb-256-pristine',
        color: 'Space Black',
        storage: '256GB',
        condition: 'Pristine',
        price: 849,
        originalPrice: 1249,
        stock: 2,
        batteryHealth: 100,
      },
      {
        id: '2-silver-128-excellent',
        color: 'Silver',
        storage: '128GB',
        condition: 'Excellent',
        price: 629,
        originalPrice: 999,
        stock: 6,
        batteryHealth: 92,
      },
      {
        id: '2-silver-256-excellent',
        color: 'Silver',
        storage: '256GB',
        condition: 'Excellent',
        price: 729,
        originalPrice: 1099,
        stock: 4,
        batteryHealth: 92,
      },
      {
        id: '2-silver-128-pristine',
        color: 'Silver',
        storage: '128GB',
        condition: 'Pristine',
        price: 749,
        originalPrice: 1149,
        stock: 2,
        batteryHealth: 100,
      },
      {
        id: '2-gold-128-excellent',
        color: 'Gold',
        storage: '128GB',
        condition: 'Excellent',
        price: 629,
        originalPrice: 999,
        stock: 7,
        batteryHealth: 92,
      },
      {
        id: '2-gold-256-excellent',
        color: 'Gold',
        storage: '256GB',
        condition: 'Excellent',
        price: 729,
        originalPrice: 1099,
        stock: 3,
        batteryHealth: 92,
      },
      {
        id: '2-gold-128-pristine',
        color: 'Gold',
        storage: '128GB',
        condition: 'Pristine',
        price: 749,
        originalPrice: 1149,
        stock: 1,
        batteryHealth: 100,
      }
    ]
  },
  {
    id: '3',
    model: 'Pixel 8 Pro',
    brand: 'Google',
    category: 'Phones',
    price: 699,
    originalPrice: 999,
    grade: 'Excellent',
    batteryHealth: 95,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/pixel-8-pro.png',
    galleryImages: [
      '/assets/pixel-8-pro.png',
      '/assets/nnCyJ3CuEgYe.jpg',
      '/assets/DRdEaOalbpKP.jpg',
      '/assets/NGZkbbow4CIm.jpg',
      '/assets/xKrBA0WkKCOR.jpg',
    ],
    isCertified: true,
    stock: 15,
    conditionDescription: 'Excellent condition with minimal wear. Google Tensor G3 AI features fully operational. Gorilla Glass Victus 2 display pristine and responsive. All cameras functioning perfectly with exceptional image quality. Includes USB-C charger and complete documentation.',
    specs: {
      network: 'GSM / HSPA / LTE / 5G',
      body: '162.6 x 76.5 x 8.8 mm, 213g; Glass front (Gorilla Glass Victus 2), glass back (Gorilla Glass Victus 2), aluminum frame',
      display: '6.7" LTPO OLED, 120Hz, HDR10+, 1600 nits (HBM), 2400 nits (peak)',
      platform: 'Android 14; Google Tensor G3 (4 nm); Nona-core CPU; Immortalis-G715s MC10 GPU',
      storage: '128GB/256GB/512GB/1TB 12GB RAM, UFS 3.1',
      mainCamera: '50 MP (wide) + 48 MP (telephoto, 5x optical) + 48 MP (ultrawide)',
      selfieCamera: '10.5 MP (ultrawide)',
      sound: 'Stereo speakers; No 3.5mm jack',
      comms: 'Wi-Fi 802.11 a/b/g/n/ac/6e/7, Bluetooth 5.3, NFC, USB Type-C 3.2',
      features: 'Fingerprint (under display, optical), thermometer (skin temperature), Ultra Wideband (UWB) support',
      battery: 'Li-Ion 5050 mAh, non-removable; 30W wired, 23W wireless'
    },
    colorOptions: ['Midnight', 'Starlight', 'Blue'],
    storageOptions: ['128GB'],
    conditionOptions: ['Good'],
    variants: [
      {
        id: '3-midnight-128-good',
        color: 'Midnight',
        storage: '128GB',
        condition: 'Good',
        price: 399,
        originalPrice: 749,
        stock: 20,
        batteryHealth: 88,
      },
      {
        id: '3-midnight-256-good',
        color: 'Midnight',
        storage: '256GB',
        condition: 'Good',
        price: 499,
        originalPrice: 849,
        stock: 12,
        batteryHealth: 88,
      },
      {
        id: '3-midnight-128-excellent',
        color: 'Midnight',
        storage: '128GB',
        condition: 'Excellent',
        price: 549,
        originalPrice: 899,
        stock: 8,
        batteryHealth: 95,
      },
      {
        id: '3-midnight-256-excellent',
        color: 'Midnight',
        storage: '256GB',
        condition: 'Excellent',
        price: 649,
        originalPrice: 999,
        stock: 5,
        batteryHealth: 95,
      },
      {
        id: '3-starlight-128-good',
        color: 'Starlight',
        storage: '128GB',
        condition: 'Good',
        price: 399,
        originalPrice: 749,
        stock: 15,
        batteryHealth: 88,
      },
      {
        id: '3-starlight-256-good',
        color: 'Starlight',
        storage: '256GB',
        condition: 'Good',
        price: 499,
        originalPrice: 849,
        stock: 10,
        batteryHealth: 88,
      },
      {
        id: '3-starlight-128-excellent',
        color: 'Starlight',
        storage: '128GB',
        condition: 'Excellent',
        price: 549,
        originalPrice: 899,
        stock: 6,
        batteryHealth: 95,
      },
      {
        id: '3-blue-128-good',
        color: 'Blue',
        storage: '128GB',
        condition: 'Good',
        price: 399,
        originalPrice: 749,
        stock: 18,
        batteryHealth: 88,
      },
      {
        id: '3-blue-256-good',
        color: 'Blue',
        storage: '256GB',
        condition: 'Good',
        price: 499,
        originalPrice: 849,
        stock: 9,
        batteryHealth: 88,
      },
      {
        id: '3-blue-128-excellent',
        color: 'Blue',
        storage: '128GB',
        condition: 'Excellent',
        price: 549,
        originalPrice: 899,
        stock: 7,
        batteryHealth: 95,
      }
    ]
  },
  {
    id: '4',
    model: 'iPhone 12 Pro',
    brand: 'Apple',
    category: 'Phones',
    price: 349,
    originalPrice: 899,
    grade: 'Excellent',
    batteryHealth: 90,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/iphone-12-pro.png',
    galleryImages: [
      '/assets/iphone-12-pro.png',
      '/assets/YUYFZeFzWLMA.png',
      '/assets/y0wXjoNpojxp.png',
      '/assets/ybNb5k0B7nvc.png',
      '/assets/xKrBA0WkKCOR.jpg',
    ],
    isCertified: true,
    stock: 8,
    conditionDescription: 'Excellent condition with minimal signs of use. Professional refurbishing process completed with full diagnostics. All cameras and sensors working perfectly. Includes original charger and complete documentation. Ready to use immediately.',
    specs: {
      display: '6.1" Super Retina XDR OLED',
      processor: 'Apple A14 Bionic',
      camera: '12MP Triple System + LiDAR',
      battery: '2815 mAh',
      ram: '6GB',
      os: 'iOS 14',
      storage: '128GB'
    },
    colorOptions: ['Pacific Blue', 'Gold', 'Silver'],
    storageOptions: ['128GB', '256GB'],
    conditionOptions: ['Excellent'],
    variants: [
      {
        id: '4-pb-128-excellent',
        color: 'Pacific Blue',
        storage: '128GB',
        condition: 'Excellent',
        price: 349,
        originalPrice: 899,
        stock: 8,
        batteryHealth: 90,
      },
      {
        id: '4-pb-256-excellent',
        color: 'Pacific Blue',
        storage: '256GB',
        condition: 'Excellent',
        price: 399,
        originalPrice: 949,
        stock: 5,
        batteryHealth: 90,
      },
      {
        id: '4-gold-128-excellent',
        color: 'Gold',
        storage: '128GB',
        condition: 'Excellent',
        price: 349,
        originalPrice: 899,
        stock: 6,
        batteryHealth: 90,
      },
      {
        id: '4-gold-256-excellent',
        color: 'Gold',
        storage: '256GB',
        condition: 'Excellent',
        price: 399,
        originalPrice: 949,
        stock: 4,
        batteryHealth: 90,
      },
      {
        id: '4-silver-128-excellent',
        color: 'Silver',
        storage: '128GB',
        condition: 'Excellent',
        price: 349,
        originalPrice: 899,
        stock: 7,
        batteryHealth: 90,
      },
      {
        id: '4-silver-256-excellent',
        color: 'Silver',
        storage: '256GB',
        condition: 'Excellent',
        price: 399,
        originalPrice: 949,
        stock: 3,
        batteryHealth: 90,
      }
    ]
  }
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'phones',
    name: 'Smartphones',
    imageUrl: '/assets/cat-smartphones.png',
    description: 'Refurbished and certified smartphones from top brands',
    productCount: 150,
    children: [
      {
        id: 'phones-apple',
        name: 'Apple iPhone',
        imageUrl: '/assets/iphone-15-pro-max.png',
        parent: 'phones',
        description: 'iPhone 15, 14, 13, 12, SE Series',
        productCount: 45,
      },
      {
        id: 'phones-samsung',
        name: 'Samsung Galaxy',
        imageUrl: '/assets/samsung-s24-ultra.png',
        parent: 'phones',
        description: 'S24, S23, Z Fold, A Series',
        productCount: 38,
      },
      {
        id: 'phones-google',
        name: 'Google Pixel',
        imageUrl: '/assets/pixel-8-pro.png',
        parent: 'phones',
        description: 'Pixel 8, 7, 6, Pro & A Series',
        productCount: 22,
      },
      {
        id: 'phones-other',
        name: 'Other Brands',
        imageUrl: '/assets/cat-accessories.png',
        parent: 'phones',
        description: 'Sony, Motorola, Nothing, Xiaomi',
        productCount: 45,
      }
    ]
  },
  {
    id: 'tablets',
    name: 'Tablets & iPads',
    imageUrl: '/assets/cat-tablets.png',
    description: 'Refurbished iPads and Android Tablets',
    productCount: 42,
    children: [
      {
        id: 'tablets-ipad',
        name: 'Apple iPad',
        imageUrl: '/assets/cat-tablets.png',
        parent: 'tablets',
        description: 'iPad Pro, Air, Mini & Standard',
        productCount: 28,
      },
      {
        id: 'tablets-samsung',
        name: 'Samsung Tab',
        imageUrl: '/assets/samsung-s24-ultra.png',
        parent: 'tablets',
        description: 'Galaxy Tab S & A Series',
        productCount: 14,
      }
    ]
  },
  {
    id: 'wearables',
    name: 'Smartwatches',
    imageUrl: '/assets/cat-smartwatches.png',
    description: 'Refurbished Apple Watch and Galaxy Watch',
    productCount: 25,
    children: [
      {
        id: 'wearables-apple',
        name: 'Apple Watch',
        imageUrl: '/assets/cat-smartwatches.png',
        parent: 'wearables',
        description: 'Series 9, 8, Ultra & SE',
        productCount: 18,
      },
      {
        id: 'wearables-samsung',
        name: 'Galaxy Watch',
        imageUrl: '/assets/cat-smartwatches.png',
        parent: 'wearables',
        description: 'Watch 6, 5, 4 & Classic',
        productCount: 7,
      }
    ]
  },
  {
    id: 'accessories',
    name: 'Accessories',
    imageUrl: '/assets/cat-accessories.png',
    description: 'Chargers, Cases, and Headphones',
    productCount: 85
  }
];
