import { Product, Category } from './types';

export const MOCK_PHONES: Product[] = [
  // --- APPLE ---
  {
    id: 'apple-iphone-15-pro-max',
    model: 'iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'Phones',
    price: 849,
    originalPrice: 1199,
    grade: 'Pristine',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/iphone-15-pro-max.png',
    isCertified: true,
    stock: 12,
    specs: {
      display: '6.7" Super Retina XDR OLED, 120Hz',
      processor: 'A17 Pro',
      camera: '48MP Triple System',
      battery: '4441 mAh',
      ram: '8GB',
      storage: '256GB/512GB/1TB'
    },
    variants: [
      { id: 'v1', color: 'Natural Titanium', storage: '256GB', price: 849, originalPrice: 1199, stock: 5 },
      { id: 'v2', color: 'Blue Titanium', storage: '512GB', price: 949, originalPrice: 1399, stock: 3 }
    ]
  },
  {
    id: 'apple-iphone-14-pro',
    model: 'iPhone 14 Pro',
    brand: 'Apple',
    category: 'Phones',
    price: 649,
    originalPrice: 999,
    grade: 'Excellent',
    batteryHealth: 92,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/iphone-12-pro.png', // Fallback
    isCertified: true,
    stock: 18,
    specs: {
      display: '6.1" Super Retina XDR OLED',
      processor: 'A16 Bionic',
      camera: '48MP Triple System',
      storage: '128GB/256GB/512GB'
    }
  },
  {
    id: 'apple-iphone-13',
    model: 'iPhone 13',
    brand: 'Apple',
    category: 'Phones',
    price: 399,
    originalPrice: 749,
    grade: 'Excellent',
    batteryHealth: 88,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/iphone-12-pro.png',
    isCertified: true,
    stock: 25,
    specs: { display: '6.1" OLED', processor: 'A15 Bionic', camera: '12MP Dual', storage: '128GB' }
  },
  {
    id: 'apple-iphone-12',
    model: 'iPhone 12',
    brand: 'Apple',
    category: 'Phones',
    price: 299,
    originalPrice: 699,
    grade: 'Good',
    batteryHealth: 85,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/iphone-12-pro.png',
    isCertified: true,
    stock: 30,
    specs: { display: '6.1" OLED', processor: 'A14 Bionic', storage: '64GB/128GB' }
  },
  {
    id: 'apple-iphone-11',
    model: 'iPhone 11',
    brand: 'Apple',
    category: 'Phones',
    price: 199,
    originalPrice: 599,
    grade: 'Good',
    batteryHealth: 82,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/iphone-12-pro.png',
    isCertified: true,
    stock: 40,
    specs: { display: '6.1" Liquid Retina', processor: 'A13 Bionic', storage: '64GB' }
  },

  // --- SAMSUNG ---
  {
    id: 'samsung-s24-ultra',
    model: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Phones',
    price: 749,
    originalPrice: 1249,
    grade: 'Pristine',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/samsung-s24-ultra.png',
    isCertified: true,
    stock: 10,
    specs: { display: '6.8" Dynamic AMOLED 2X', processor: 'Snapdragon 8 Gen 3', camera: '200MP Quad', storage: '256GB' }
  },
  {
    id: 'samsung-s23-ultra',
    model: 'Galaxy S23 Ultra',
    brand: 'Samsung',
    category: 'Phones',
    price: 549,
    originalPrice: 1149,
    grade: 'Excellent',
    batteryHealth: 94,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/samsung-s24-ultra.png',
    isCertified: true,
    stock: 15,
    specs: { display: '6.8" AMOLED', processor: 'Snapdragon 8 Gen 2', camera: '200MP Quad' }
  },
  {
    id: 'samsung-s22',
    model: 'Galaxy S22',
    brand: 'Samsung',
    category: 'Phones',
    price: 249,
    originalPrice: 769,
    grade: 'Good',
    batteryHealth: 87,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/samsung-s24-ultra.png',
    isCertified: true,
    stock: 22,
    specs: { display: '6.1" AMOLED', processor: 'Exynos 2200', storage: '128GB' }
  },
  {
    id: 'samsung-s21-fe',
    model: 'Galaxy S21 FE',
    brand: 'Samsung',
    category: 'Phones',
    price: 189,
    originalPrice: 699,
    grade: 'Excellent',
    batteryHealth: 89,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/samsung-s24-ultra.png',
    isCertified: true,
    stock: 28,
    specs: { display: '6.4" AMOLED', processor: 'Snapdragon 888' }
  },

  // --- GOOGLE ---
  {
    id: 'google-pixel-8-pro',
    model: 'Pixel 8 Pro',
    brand: 'Google',
    category: 'Phones',
    price: 469,
    originalPrice: 999,
    grade: 'Pristine',
    batteryHealth: 98,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/pixel-8-pro.png',
    isCertified: true,
    stock: 14,
    specs: { display: '6.7" LTPO OLED', processor: 'Google Tensor G3', camera: '50MP Triple' }
  },
  {
    id: 'google-pixel-7a',
    model: 'Pixel 7a',
    brand: 'Google',
    category: 'Phones',
    price: 249,
    originalPrice: 449,
    grade: 'Excellent',
    batteryHealth: 95,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/pixel-8-pro.png',
    isCertified: true,
    stock: 20,
    specs: { display: '6.1" OLED', processor: 'Tensor G2', storage: '128GB' }
  },
  {
    id: 'google-pixel-6',
    model: 'Pixel 6',
    brand: 'Google',
    category: 'Phones',
    price: 159,
    originalPrice: 599,
    grade: 'Good',
    batteryHealth: 84,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/pixel-8-pro.png',
    isCertified: true,
    stock: 35,
    specs: { display: '6.4" AMOLED', processor: 'Google Tensor', storage: '128GB' }
  },

  // --- ONEPLUS ---
  {
    id: 'oneplus-12',
    model: 'OnePlus 12',
    brand: 'OnePlus',
    category: 'Phones',
    price: 599,
    originalPrice: 849,
    grade: 'Pristine',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-smartphones.png',
    isCertified: true,
    stock: 8,
    specs: { display: '6.82" AMOLED', processor: 'Snapdragon 8 Gen 3', storage: '256GB' }
  },
  {
    id: 'oneplus-11',
    model: 'OnePlus 11',
    brand: 'OnePlus',
    category: 'Phones',
    price: 399,
    originalPrice: 729,
    grade: 'Excellent',
    batteryHealth: 92,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-smartphones.png',
    isCertified: true,
    stock: 12,
    specs: { display: '6.7" AMOLED', processor: 'Snapdragon 8 Gen 2' }
  },
  {
    id: 'oneplus-9-pro',
    model: 'OnePlus 9 Pro',
    brand: 'OnePlus',
    category: 'Phones',
    price: 229,
    originalPrice: 829,
    grade: 'Good',
    batteryHealth: 86,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-smartphones.png',
    isCertified: true,
    stock: 15,
    specs: { display: '6.7" AMOLED', processor: 'Snapdragon 888' }
  },

  // --- MOTOROLA ---
  {
    id: 'motorola-edge-40',
    model: 'Edge 40',
    brand: 'Motorola',
    category: 'Phones',
    price: 279,
    originalPrice: 529,
    grade: 'Excellent',
    batteryHealth: 96,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-smartphones.png',
    isCertified: true,
    stock: 10,
    specs: { display: '6.55" P-OLED', processor: 'Dimensity 8020', storage: '256GB' }
  },
  {
    id: 'motorola-g84',
    model: 'Moto G84',
    brand: 'Motorola',
    category: 'Phones',
    price: 149,
    originalPrice: 249,
    grade: 'Pristine',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-smartphones.png',
    isCertified: true,
    stock: 25,
    specs: { display: '6.5" P-OLED', processor: 'Snapdragon 695', storage: '256GB' }
  },

  // --- ACCESSORIES ---
  {
    id: 'apple-airpods-pro-2',
    model: 'AirPods Pro (2nd Gen)',
    brand: 'Apple',
    category: 'Accessories',
    price: 169,
    originalPrice: 229,
    grade: 'Pristine',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 50,
    specs: { features: 'Active Noise Cancellation, Transparency Mode, H2 Chip' }
  },
  {
    id: 'samsung-buds-2-pro',
    model: 'Galaxy Buds2 Pro',
    brand: 'Samsung',
    category: 'Accessories',
    price: 99,
    originalPrice: 219,
    grade: 'Pristine',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 45,
    specs: { features: '24-bit Hi-Fi Audio, Intelligent ANC, IPX7' }
  },
  {
    id: 'google-pixel-buds-pro',
    model: 'Pixel Buds Pro',
    brand: 'Google',
    category: 'Accessories',
    price: 89,
    originalPrice: 179,
    grade: 'Excellent',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 30,
    specs: { features: 'Active Noise Cancellation, Silent Seal, Hey Google' }
  },

  // --- TABLETS ---
  {
    id: 'apple-ipad-pro-12-9-m2',
    model: 'iPad Pro 12.9" M2',
    brand: 'Apple',
    category: 'Tablets',
    price: 749,
    originalPrice: 1249,
    grade: 'Excellent',
    batteryHealth: 94,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-tablets.png',
    isCertified: true,
    stock: 9,
    specs: { display: '12.9" Liquid Retina XDR', processor: 'Apple M2', storage: '256GB', features: 'Wi-Fi + Cellular, Apple Pencil support' }
  },
  {
    id: 'samsung-galaxy-tab-s9',
    model: 'Galaxy Tab S9',
    brand: 'Samsung',
    category: 'Tablets',
    price: 469,
    originalPrice: 799,
    grade: 'Pristine',
    batteryHealth: 98,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-tablets.png',
    isCertified: true,
    stock: 13,
    specs: { display: '11" Dynamic AMOLED 2X', processor: 'Snapdragon 8 Gen 2', storage: '128GB', features: 'S Pen included, IP68' }
  },
  {
    id: 'microsoft-surface-go-3',
    model: 'Surface Go 3',
    brand: 'Microsoft',
    category: 'Tablets',
    price: 249,
    originalPrice: 529,
    grade: 'Good',
    batteryHealth: 88,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-tablets.png',
    isCertified: true,
    stock: 16,
    specs: { display: '10.5" PixelSense touchscreen', processor: 'Intel Pentium Gold', ram: '8GB', storage: '128GB SSD' }
  },

  // --- COMPUTING ---
  {
    id: 'apple-macbook-air-m2-13',
    model: 'MacBook Air 13" M2',
    brand: 'Apple',
    category: 'Computing',
    price: 799,
    originalPrice: 1249,
    grade: 'Excellent',
    batteryHealth: 92,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-tablets.png',
    isCertified: true,
    stock: 7,
    specs: { display: '13.6" Liquid Retina', processor: 'Apple M2', ram: '8GB', storage: '256GB SSD', features: 'MagSafe, Touch ID' }
  },
  {
    id: 'dell-xps-13-9315',
    model: 'XPS 13 9315',
    brand: 'Dell',
    category: 'Computing',
    price: 529,
    originalPrice: 999,
    grade: 'Excellent',
    batteryHealth: 90,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-tablets.png',
    isCertified: true,
    stock: 11,
    specs: { display: '13.4" InfinityEdge FHD+', processor: 'Intel Core i7', ram: '16GB', storage: '512GB SSD' }
  },
  {
    id: 'lenovo-thinkpad-x1-carbon-g9',
    model: 'ThinkPad X1 Carbon Gen 9',
    brand: 'Lenovo',
    category: 'Computing',
    price: 599,
    originalPrice: 1399,
    grade: 'Good',
    batteryHealth: 86,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-tablets.png',
    isCertified: true,
    stock: 10,
    specs: { display: '14" FHD IPS', processor: 'Intel Core i5', ram: '16GB', storage: '512GB SSD', features: 'Business grade, backlit keyboard' }
  },

  // --- GAMING ---
  {
    id: 'sony-playstation-5-disc',
    model: 'PlayStation 5 Disc Edition',
    brand: 'Sony',
    category: 'Gaming',
    price: 359,
    originalPrice: 479,
    grade: 'Excellent',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 14,
    specs: { processor: 'AMD Zen 2 CPU', storage: '825GB SSD', features: '4K gaming, DualSense controller included' }
  },
  {
    id: 'microsoft-xbox-series-x',
    model: 'Xbox Series X',
    brand: 'Microsoft',
    category: 'Gaming',
    price: 329,
    originalPrice: 449,
    grade: 'Excellent',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 12,
    specs: { processor: 'Custom AMD Zen 2', storage: '1TB SSD', features: '4K 120fps, Game Pass ready' }
  },
  {
    id: 'nintendo-switch-oled',
    model: 'Switch OLED',
    brand: 'Nintendo',
    category: 'Gaming',
    price: 219,
    originalPrice: 309,
    grade: 'Good',
    batteryHealth: 89,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 20,
    specs: { display: '7" OLED touchscreen', storage: '64GB', features: 'Dock included, detachable Joy-Con controllers' }
  },

  // --- SMARTWATCHES ---
  {
    id: 'apple-watch-series-9',
    model: 'Watch Series 9',
    brand: 'Apple',
    category: 'Smartwatches',
    price: 269,
    originalPrice: 429,
    grade: 'Pristine',
    batteryHealth: 97,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-smartwatches.png',
    isCertified: true,
    stock: 22,
    specs: { display: 'Always-On Retina LTPO OLED', processor: 'S9 SiP', features: 'GPS, health sensors, watchOS' }
  },
  {
    id: 'samsung-galaxy-watch-6',
    model: 'Galaxy Watch6',
    brand: 'Samsung',
    category: 'Smartwatches',
    price: 149,
    originalPrice: 289,
    grade: 'Excellent',
    batteryHealth: 93,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-smartwatches.png',
    isCertified: true,
    stock: 24,
    specs: { display: 'Super AMOLED sapphire crystal', processor: 'Exynos W930', features: 'Wear OS, body composition tracking' }
  },
  {
    id: 'google-pixel-watch-2',
    model: 'Pixel Watch 2',
    brand: 'Google',
    category: 'Smartwatches',
    price: 179,
    originalPrice: 349,
    grade: 'Excellent',
    batteryHealth: 94,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-smartwatches.png',
    isCertified: true,
    stock: 17,
    specs: { display: 'AMOLED Gorilla Glass 5', processor: 'Qualcomm 5100', features: 'Fitbit health tracking, Wear OS' }
  },

  // --- SMART TVS ---
  {
    id: 'samsung-frame-55-qled',
    model: 'The Frame 55" QLED',
    brand: 'Samsung',
    category: 'TV',
    price: 649,
    originalPrice: 1199,
    grade: 'Excellent',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 5,
    specs: { display: '55" 4K QLED', processor: 'Quantum Processor 4K', features: 'Art Mode, HDR10+, smart TV apps' }
  },
  {
    id: 'lg-c2-48-oled',
    model: 'C2 48" OLED',
    brand: 'LG',
    category: 'TV',
    price: 699,
    originalPrice: 1299,
    grade: 'Good',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 4,
    specs: { display: '48" 4K OLED evo', processor: 'α9 Gen5 AI Processor', features: 'HDMI 2.1, 120Hz, webOS' }
  },
  {
    id: 'sony-bravia-xr-55',
    model: 'Bravia XR 55" 4K',
    brand: 'Sony',
    category: 'TV',
    price: 579,
    originalPrice: 1099,
    grade: 'Excellent',
    batteryHealth: 100,
    warrantyMonths: 12,
    returnDays: 30,
    imageUrl: '/assets/cat-accessories.png',
    isCertified: true,
    stock: 6,
    specs: { display: '55" 4K LED', processor: 'Cognitive Processor XR', features: 'Google TV, Dolby Vision, Acoustic Multi-Audio' }
  }
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'phones',
    name: 'Smartphones',
    imageUrl: '/assets/cat-smartphones.png',
    description: 'UK\'s top 5 brands: Apple, Samsung, Google, OnePlus & Motorola',
    productCount: 17,
    children: [
      {
        id: 'phones-apple',
        name: 'Apple iPhone',
        imageUrl: '/assets/iphone-15-pro-max.png',
        parent: 'phones',
        description: 'iPhone 15 down to iPhone 11',
        productCount: 45,
      },
      {
        id: 'phones-samsung',
        name: 'Samsung Galaxy',
        imageUrl: '/assets/samsung-s24-ultra.png',
        parent: 'phones',
        description: 'S24 Ultra to S20 Series',
        productCount: 38,
      },
      {
        id: 'phones-google',
        name: 'Google Pixel',
        imageUrl: '/assets/pixel-8-pro.png',
        parent: 'phones',
        description: 'Pixel 8 Pro to Pixel 5',
        productCount: 22,
      }
    ]
  },
  {
    id: 'accessories',
    name: 'Accessories',
    imageUrl: '/assets/cat-accessories.png',
    description: 'Genuine chargers, cases, and audio for your mobile',
    productCount: 3
  },
  {
    id: 'tablets',
    name: 'Tablets',
    imageUrl: '/assets/cat-tablets.png',
    description: 'iPad, Galaxy Tab, and Windows tablets ready for work or streaming',
    productCount: 3
  },
  {
    id: 'computing',
    name: 'Laptops',
    imageUrl: '/assets/cat-tablets.png',
    description: 'Certified MacBook, Dell, and Lenovo laptops for everyday work',
    productCount: 3
  },
  {
    id: 'gaming',
    name: 'Gaming consoles',
    imageUrl: '/assets/cat-accessories.png',
    description: 'PlayStation, Xbox, and Nintendo hardware with warranty cover',
    productCount: 3
  },
  {
    id: 'watches',
    name: 'Smartwatches',
    imageUrl: '/assets/cat-smartwatches.png',
    description: 'Apple Watch, Galaxy Watch, and Pixel Watch models',
    productCount: 3
  },
  {
    id: 'tv',
    name: 'Smart TVs',
    imageUrl: '/assets/cat-accessories.png',
    description: 'Refurbished 4K OLED, QLED, and smart TVs for home cinema',
    productCount: 3
  }
];
