/**
 * Generated by scripts/generate-responsive-images.mjs — do not edit by hand.
 *
 * Original public path -> intrinsic size and AVIF/WebP srcsets. Anything not
 * listed here (staff uploads, Cloudinary URLs) renders from its original URL.
 */
export interface ResponsiveImage {
  width: number;
  height: number;
  avif: string;
  webp: string;
}

export const RESPONSIVE_IMAGES: Record<string, ResponsiveImage> = {
  '/assets/hero-campaign-apple-desktop-20261004.png': {
    width: 2172,
    height: 724,
    avif: '/assets/responsive/hero-campaign-apple-desktop-20261004-828w.avif 828w, /assets/responsive/hero-campaign-apple-desktop-20261004-1280w.avif 1280w, /assets/responsive/hero-campaign-apple-desktop-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-apple-desktop-20261004-2172w.avif 2172w',
    webp: '/assets/responsive/hero-campaign-apple-desktop-20261004-828w.webp 828w, /assets/responsive/hero-campaign-apple-desktop-20261004-1280w.webp 1280w, /assets/responsive/hero-campaign-apple-desktop-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-apple-desktop-20261004-2172w.webp 2172w'
  },
  '/assets/hero-campaign-apple-desktop-4x16-20261004.png': {
    width: 1920,
    height: 462,
    avif: '/assets/responsive/hero-campaign-apple-desktop-4x16-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-apple-desktop-4x16-20261004-1920w.avif 1920w',
    webp: '/assets/responsive/hero-campaign-apple-desktop-4x16-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-apple-desktop-4x16-20261004-1920w.webp 1920w'
  },
  '/assets/hero-campaign-apple-mobile-safe-20261004.png': {
    width: 1122,
    height: 1402,
    avif: '/assets/responsive/hero-campaign-apple-mobile-safe-20261004-640w.avif 640w, /assets/responsive/hero-campaign-apple-mobile-safe-20261004-828w.avif 828w, /assets/responsive/hero-campaign-apple-mobile-safe-20261004-1122w.avif 1122w',
    webp: '/assets/responsive/hero-campaign-apple-mobile-safe-20261004-640w.webp 640w, /assets/responsive/hero-campaign-apple-mobile-safe-20261004-828w.webp 828w, /assets/responsive/hero-campaign-apple-mobile-safe-20261004-1122w.webp 1122w'
  },
  '/assets/hero-campaign-samsung-desktop-20261004.png': {
    width: 2172,
    height: 724,
    avif: '/assets/responsive/hero-campaign-samsung-desktop-20261004-828w.avif 828w, /assets/responsive/hero-campaign-samsung-desktop-20261004-1280w.avif 1280w, /assets/responsive/hero-campaign-samsung-desktop-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-samsung-desktop-20261004-2172w.avif 2172w',
    webp: '/assets/responsive/hero-campaign-samsung-desktop-20261004-828w.webp 828w, /assets/responsive/hero-campaign-samsung-desktop-20261004-1280w.webp 1280w, /assets/responsive/hero-campaign-samsung-desktop-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-samsung-desktop-20261004-2172w.webp 2172w'
  },
  '/assets/hero-campaign-samsung-desktop-4x16-20261004.png': {
    width: 1920,
    height: 462,
    avif: '/assets/responsive/hero-campaign-samsung-desktop-4x16-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-samsung-desktop-4x16-20261004-1920w.avif 1920w',
    webp: '/assets/responsive/hero-campaign-samsung-desktop-4x16-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-samsung-desktop-4x16-20261004-1920w.webp 1920w'
  },
  '/assets/hero-campaign-samsung-mobile-safe-20261004.png': {
    width: 1122,
    height: 1402,
    avif: '/assets/responsive/hero-campaign-samsung-mobile-safe-20261004-640w.avif 640w, /assets/responsive/hero-campaign-samsung-mobile-safe-20261004-828w.avif 828w, /assets/responsive/hero-campaign-samsung-mobile-safe-20261004-1122w.avif 1122w',
    webp: '/assets/responsive/hero-campaign-samsung-mobile-safe-20261004-640w.webp 640w, /assets/responsive/hero-campaign-samsung-mobile-safe-20261004-828w.webp 828w, /assets/responsive/hero-campaign-samsung-mobile-safe-20261004-1122w.webp 1122w'
  },
  '/assets/hero-campaign-pixel-desktop-20261004.png': {
    width: 2172,
    height: 724,
    avif: '/assets/responsive/hero-campaign-pixel-desktop-20261004-828w.avif 828w, /assets/responsive/hero-campaign-pixel-desktop-20261004-1280w.avif 1280w, /assets/responsive/hero-campaign-pixel-desktop-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-pixel-desktop-20261004-2172w.avif 2172w',
    webp: '/assets/responsive/hero-campaign-pixel-desktop-20261004-828w.webp 828w, /assets/responsive/hero-campaign-pixel-desktop-20261004-1280w.webp 1280w, /assets/responsive/hero-campaign-pixel-desktop-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-pixel-desktop-20261004-2172w.webp 2172w'
  },
  '/assets/hero-campaign-pixel-desktop-4x16-20261004.png': {
    width: 1920,
    height: 462,
    avif: '/assets/responsive/hero-campaign-pixel-desktop-4x16-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-pixel-desktop-4x16-20261004-1920w.avif 1920w',
    webp: '/assets/responsive/hero-campaign-pixel-desktop-4x16-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-pixel-desktop-4x16-20261004-1920w.webp 1920w'
  },
  '/assets/hero-campaign-pixel-mobile-safe-20261004.png': {
    width: 1122,
    height: 1402,
    avif: '/assets/responsive/hero-campaign-pixel-mobile-safe-20261004-640w.avif 640w, /assets/responsive/hero-campaign-pixel-mobile-safe-20261004-828w.avif 828w, /assets/responsive/hero-campaign-pixel-mobile-safe-20261004-1122w.avif 1122w',
    webp: '/assets/responsive/hero-campaign-pixel-mobile-safe-20261004-640w.webp 640w, /assets/responsive/hero-campaign-pixel-mobile-safe-20261004-828w.webp 828w, /assets/responsive/hero-campaign-pixel-mobile-safe-20261004-1122w.webp 1122w'
  },
  '/assets/hero-campaign-tablets-desktop-20261004.png': {
    width: 2172,
    height: 724,
    avif: '/assets/responsive/hero-campaign-tablets-desktop-20261004-828w.avif 828w, /assets/responsive/hero-campaign-tablets-desktop-20261004-1280w.avif 1280w, /assets/responsive/hero-campaign-tablets-desktop-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-tablets-desktop-20261004-2172w.avif 2172w',
    webp: '/assets/responsive/hero-campaign-tablets-desktop-20261004-828w.webp 828w, /assets/responsive/hero-campaign-tablets-desktop-20261004-1280w.webp 1280w, /assets/responsive/hero-campaign-tablets-desktop-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-tablets-desktop-20261004-2172w.webp 2172w'
  },
  '/assets/hero-campaign-tablets-desktop-4x16-20261004.png': {
    width: 1920,
    height: 462,
    avif: '/assets/responsive/hero-campaign-tablets-desktop-4x16-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-tablets-desktop-4x16-20261004-1920w.avif 1920w',
    webp: '/assets/responsive/hero-campaign-tablets-desktop-4x16-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-tablets-desktop-4x16-20261004-1920w.webp 1920w'
  },
  '/assets/hero-campaign-tablets-mobile-safe-20261004.png': {
    width: 1122,
    height: 1402,
    avif: '/assets/responsive/hero-campaign-tablets-mobile-safe-20261004-640w.avif 640w, /assets/responsive/hero-campaign-tablets-mobile-safe-20261004-828w.avif 828w, /assets/responsive/hero-campaign-tablets-mobile-safe-20261004-1122w.avif 1122w',
    webp: '/assets/responsive/hero-campaign-tablets-mobile-safe-20261004-640w.webp 640w, /assets/responsive/hero-campaign-tablets-mobile-safe-20261004-828w.webp 828w, /assets/responsive/hero-campaign-tablets-mobile-safe-20261004-1122w.webp 1122w'
  },
  '/assets/hero-campaign-accessories-desktop-20261004.png': {
    width: 2172,
    height: 724,
    avif: '/assets/responsive/hero-campaign-accessories-desktop-20261004-828w.avif 828w, /assets/responsive/hero-campaign-accessories-desktop-20261004-1280w.avif 1280w, /assets/responsive/hero-campaign-accessories-desktop-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-accessories-desktop-20261004-2172w.avif 2172w',
    webp: '/assets/responsive/hero-campaign-accessories-desktop-20261004-828w.webp 828w, /assets/responsive/hero-campaign-accessories-desktop-20261004-1280w.webp 1280w, /assets/responsive/hero-campaign-accessories-desktop-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-accessories-desktop-20261004-2172w.webp 2172w'
  },
  '/assets/hero-campaign-accessories-desktop-4x16-20261004.png': {
    width: 1920,
    height: 462,
    avif: '/assets/responsive/hero-campaign-accessories-desktop-4x16-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-accessories-desktop-4x16-20261004-1920w.avif 1920w',
    webp: '/assets/responsive/hero-campaign-accessories-desktop-4x16-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-accessories-desktop-4x16-20261004-1920w.webp 1920w'
  },
  '/assets/hero-campaign-accessories-mobile-safe-20261004.png': {
    width: 1122,
    height: 1402,
    avif: '/assets/responsive/hero-campaign-accessories-mobile-safe-20261004-640w.avif 640w, /assets/responsive/hero-campaign-accessories-mobile-safe-20261004-828w.avif 828w, /assets/responsive/hero-campaign-accessories-mobile-safe-20261004-1122w.avif 1122w',
    webp: '/assets/responsive/hero-campaign-accessories-mobile-safe-20261004-640w.webp 640w, /assets/responsive/hero-campaign-accessories-mobile-safe-20261004-828w.webp 828w, /assets/responsive/hero-campaign-accessories-mobile-safe-20261004-1122w.webp 1122w'
  },
  '/assets/hero-campaign-gaming-desktop-20261004.png': {
    width: 2172,
    height: 724,
    avif: '/assets/responsive/hero-campaign-gaming-desktop-20261004-828w.avif 828w, /assets/responsive/hero-campaign-gaming-desktop-20261004-1280w.avif 1280w, /assets/responsive/hero-campaign-gaming-desktop-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-gaming-desktop-20261004-2172w.avif 2172w',
    webp: '/assets/responsive/hero-campaign-gaming-desktop-20261004-828w.webp 828w, /assets/responsive/hero-campaign-gaming-desktop-20261004-1280w.webp 1280w, /assets/responsive/hero-campaign-gaming-desktop-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-gaming-desktop-20261004-2172w.webp 2172w'
  },
  '/assets/hero-campaign-gaming-desktop-4x16-20261004.png': {
    width: 1920,
    height: 462,
    avif: '/assets/responsive/hero-campaign-gaming-desktop-4x16-20261004-1600w.avif 1600w, /assets/responsive/hero-campaign-gaming-desktop-4x16-20261004-1920w.avif 1920w',
    webp: '/assets/responsive/hero-campaign-gaming-desktop-4x16-20261004-1600w.webp 1600w, /assets/responsive/hero-campaign-gaming-desktop-4x16-20261004-1920w.webp 1920w'
  },
  '/assets/hero-campaign-gaming-mobile-safe-20261004.png': {
    width: 1122,
    height: 1402,
    avif: '/assets/responsive/hero-campaign-gaming-mobile-safe-20261004-640w.avif 640w, /assets/responsive/hero-campaign-gaming-mobile-safe-20261004-828w.avif 828w, /assets/responsive/hero-campaign-gaming-mobile-safe-20261004-1122w.avif 1122w',
    webp: '/assets/responsive/hero-campaign-gaming-mobile-safe-20261004-640w.webp 640w, /assets/responsive/hero-campaign-gaming-mobile-safe-20261004-828w.webp 828w, /assets/responsive/hero-campaign-gaming-mobile-safe-20261004-1122w.webp 1122w'
  },
  '/assets/quality-inspection.png': {
    width: 1024,
    height: 1024,
    avif: '/assets/responsive/quality-inspection-480w.avif 480w, /assets/responsive/quality-inspection-768w.avif 768w, /assets/responsive/quality-inspection-1024w.avif 1024w',
    webp: '/assets/responsive/quality-inspection-480w.webp 480w, /assets/responsive/quality-inspection-768w.webp 768w, /assets/responsive/quality-inspection-1024w.webp 1024w'
  }
};
